#pragma once

#include <windows.h>
#include <dxgi1_6.h>

constexpr auto WINDOW_WIDTH = 1280;
constexpr auto WINDOW_HEIGHT = 720;
constexpr auto SWAP_CHAIN_BUFFER_COUNT = 3;
constexpr auto SWAP_CHAIN_BUFFER_FORMAT = DXGI_FORMAT_R8G8B8A8_UNORM;
constexpr auto CQRENDER_DEPTH_STENCIL_BUFFER_FORMAT = DXGI_FORMAT_D32_FLOAT;
constexpr auto INPUT_VIDEO_FILE_PATH = L"./media/";
constexpr auto SKIP_FRAME_COUNT = 59;
constexpr auto COMPUTE_SHADER_IMAGE_FORMAT = DXGI_FORMAT_R8G8B8A8_UNORM;
constexpr auto COMPUTE_SHADER_KC_CENTROID_INIT_FULL_RANDOM = FALSE;
constexpr auto COMPUTE_SHADER_KC_CENTROID_INIT_NO_RANDOM = FALSE;
constexpr auto COMPUTE_SHADER_KC_CENTROID_INIT_FROM_PIXEL_SET = TRUE;
constexpr auto COMPUTE_SHADER_KC_CENTROID_COUNT = 32;
constexpr auto COMPUTE_SHADER_KC_LOOP_COUNT = 20;


constexpr BYTE CQRENDER_ONUPDATE_NO_FLAG				= 0b00000000;
constexpr BYTE CQRENDER_ONUPDATE_UPDATE_SAMPLE_BUFFER	= 0b00000001;
constexpr BYTE CQRENDER_ONUPDATE_UPDATE_ONE_SECOND		= 0b00000010;

constexpr BYTE RESOURCE_NO_FLAG							= 0b00000000;
constexpr BYTE RESOURCE_NO_READBACK						= 0b00000001;
constexpr BYTE RESOURCE_NO_UPLOAD						= 0b00000010;
constexpr BYTE RESOURCE_NO_DEFAULT						= 0b00000100;

constexpr auto SUBSPACERENDER_DEPTH_STENCIL_BUFFER_FORMAT = DXGI_FORMAT_D32_FLOAT;

constexpr auto CUBELIGHTINGRENDER_DEPTH_STENCIL_BUFFER_FORMAT = DXGI_FORMAT_D32_FLOAT;

constexpr auto CLUSTERING_ITERATIONS_DEPTH_STENCIL_BUFFER_FORMAT = DXGI_FORMAT_D32_FLOAT;
constexpr auto CLUSTERING_ITERATIONS_ORIGINAL_VIDEO_FRAME_FORMAT = DXGI_FORMAT_R8G8B8A8_UNORM;
